// MASEF 2026–27 timetable, transcribed from "PLANNING MASEF.pdf" (41 weekly grids, 31/08/2026 → 11/06/2027).
// Times are Paris local time. kind: class | exam | exam-extra (⅓-temps sitting).

export type SessionKind = 'class' | 'exam' | 'exam-extra';

export interface Session {
  date: string; // YYYY-MM-DD
  start: string; // HH:MM
  end: string;
  course: string;
  title: string;
  teacher: string;
  room: string;
  kind: SessionKind;
}

export const SESSIONS: Session[] = [
  {"date": "2026-08-31", "start": "08:30", "end": "10:00", "course": "P", "title": "A review of probability theory foundations", "teacher": "Forien Nicolas", "room": "C 516", "kind": "class"},
  {"date": "2026-08-31", "start": "10:15", "end": "11:45", "course": "P", "title": "A review of probability theory foundations", "teacher": "Forien Nicolas", "room": "C 516", "kind": "class"},
  {"date": "2026-09-01", "start": "08:30", "end": "10:00", "course": "P", "title": "A review of probability theory foundations", "teacher": "Forien Nicolas", "room": "C 516", "kind": "class"},
  {"date": "2026-09-01", "start": "10:15", "end": "11:45", "course": "P", "title": "A review of probability theory foundations", "teacher": "Forien Nicolas", "room": "C 516", "kind": "class"},
  {"date": "2026-09-02", "start": "08:30", "end": "10:00", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D301", "kind": "class"},
  {"date": "2026-09-02", "start": "10:15", "end": "11:45", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D301", "kind": "class"},
  {"date": "2026-09-03", "start": "08:30", "end": "10:00", "course": "P", "title": "A review of probability theory foundations", "teacher": "Forien Nicolas", "room": "C 516", "kind": "class"},
  {"date": "2026-09-03", "start": "10:15", "end": "11:45", "course": "P", "title": "A review of probability theory foundations", "teacher": "Forien Nicolas", "room": "C 516", "kind": "class"},
  {"date": "2026-09-08", "start": "08:30", "end": "10:00", "course": "P", "title": "A review of probability theory foundations", "teacher": "Forien Nicolas", "room": "C 516", "kind": "class"},
  {"date": "2026-09-08", "start": "10:15", "end": "11:45", "course": "P", "title": "A review of probability theory foundations", "teacher": "Forien Nicolas", "room": "C 516", "kind": "class"},
  {"date": "2026-09-09", "start": "08:30", "end": "10:00", "course": "P", "title": "A review of probability theory foundations", "teacher": "Forien Nicolas", "room": "C 516", "kind": "class"},
  {"date": "2026-09-09", "start": "08:30", "end": "10:00", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-09-09", "start": "10:15", "end": "11:45", "course": "P", "title": "A review of probability theory foundations", "teacher": "Forien Nicolas", "room": "C 516", "kind": "class"},
  {"date": "2026-09-09", "start": "10:15", "end": "11:45", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-09-10", "start": "08:30", "end": "10:00", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "Amphi 11", "kind": "class"},
  {"date": "2026-09-10", "start": "10:15", "end": "11:45", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "Amphi 11", "kind": "class"},
  {"date": "2026-09-11", "start": "08:30", "end": "10:00", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-09-11", "start": "10:15", "end": "11:45", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-09-14", "start": "08:30", "end": "10:00", "course": "SCTD", "title": "Stochastic Calculus — TD", "teacher": "Cosco Clément", "room": "C 516", "kind": "class"},
  {"date": "2026-09-14", "start": "10:15", "end": "11:45", "course": "SCTD", "title": "Stochastic Calculus — TD", "teacher": "Cosco Clément", "room": "C 516", "kind": "class"},
  {"date": "2026-09-14", "start": "13:45", "end": "15:15", "course": "CPP", "title": "C++ / VBA", "teacher": "Cornaz Denis", "room": "A211", "kind": "class"},
  {"date": "2026-09-14", "start": "15:30", "end": "17:00", "course": "CPP", "title": "C++ / VBA", "teacher": "Cornaz Denis", "room": "A211", "kind": "class"},
  {"date": "2026-09-15", "start": "08:30", "end": "10:00", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-09-15", "start": "10:15", "end": "11:45", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-09-15", "start": "14:15", "end": "15:45", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-09-15", "start": "16:00", "end": "17:30", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-09-16", "start": "08:30", "end": "10:00", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "C131", "kind": "class"},
  {"date": "2026-09-16", "start": "09:00", "end": "10:30", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-09-16", "start": "10:15", "end": "11:45", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "C131", "kind": "class"},
  {"date": "2026-09-16", "start": "10:45", "end": "12:15", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-09-17", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2026-09-18", "start": "08:30", "end": "10:00", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B213", "kind": "class"},
  {"date": "2026-09-18", "start": "10:15", "end": "11:45", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B213", "kind": "class"},
  {"date": "2026-09-21", "start": "08:30", "end": "10:00", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-09-21", "start": "10:15", "end": "11:45", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-09-21", "start": "13:45", "end": "15:15", "course": "CPP", "title": "C++ / VBA", "teacher": "Cornaz Denis", "room": "A211", "kind": "class"},
  {"date": "2026-09-21", "start": "15:30", "end": "17:00", "course": "CPP", "title": "C++ / VBA", "teacher": "Cornaz Denis", "room": "A211", "kind": "class"},
  {"date": "2026-09-22", "start": "08:30", "end": "10:00", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-09-22", "start": "10:15", "end": "11:45", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-09-22", "start": "13:45", "end": "15:15", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-09-22", "start": "14:15", "end": "15:45", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-09-22", "start": "15:30", "end": "17:00", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-09-22", "start": "16:00", "end": "17:30", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-09-23", "start": "08:30", "end": "10:00", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D207", "kind": "class"},
  {"date": "2026-09-23", "start": "09:00", "end": "10:30", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-09-23", "start": "10:15", "end": "11:45", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D207", "kind": "class"},
  {"date": "2026-09-23", "start": "10:45", "end": "12:15", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-09-24", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2026-09-25", "start": "08:30", "end": "10:00", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B215", "kind": "class"},
  {"date": "2026-09-25", "start": "10:15", "end": "11:45", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B215", "kind": "class"},
  {"date": "2026-09-28", "start": "13:45", "end": "15:15", "course": "CPP", "title": "C++ / VBA", "teacher": "Cornaz Denis", "room": "A211", "kind": "class"},
  {"date": "2026-09-28", "start": "15:30", "end": "17:00", "course": "CPP", "title": "C++ / VBA", "teacher": "Cornaz Denis", "room": "A211", "kind": "class"},
  {"date": "2026-09-29", "start": "13:45", "end": "15:15", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "D202", "kind": "class"},
  {"date": "2026-09-29", "start": "14:15", "end": "15:45", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-09-29", "start": "15:30", "end": "17:00", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "D202", "kind": "class"},
  {"date": "2026-09-29", "start": "16:00", "end": "17:30", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-09-30", "start": "08:30", "end": "10:00", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-09-30", "start": "08:30", "end": "10:00", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-09-30", "start": "10:15", "end": "11:45", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-09-30", "start": "10:15", "end": "11:45", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-10-01", "start": "08:30", "end": "10:00", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "Amphi 10", "kind": "class"},
  {"date": "2026-10-01", "start": "10:15", "end": "11:45", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "Amphi 10", "kind": "class"},
  {"date": "2026-10-01", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2026-10-02", "start": "08:30", "end": "10:00", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B215", "kind": "class"},
  {"date": "2026-10-02", "start": "10:15", "end": "11:45", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B215", "kind": "class"},
  {"date": "2026-10-05", "start": "08:30", "end": "10:00", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-10-05", "start": "10:15", "end": "11:45", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-10-05", "start": "13:45", "end": "15:15", "course": "CPP", "title": "C++ / VBA", "teacher": "Cornaz Denis", "room": "A211", "kind": "class"},
  {"date": "2026-10-05", "start": "15:30", "end": "17:00", "course": "CPP", "title": "C++ / VBA", "teacher": "Cornaz Denis", "room": "A211", "kind": "class"},
  {"date": "2026-10-06", "start": "13:45", "end": "15:15", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "Amphi 11", "kind": "class"},
  {"date": "2026-10-06", "start": "14:15", "end": "15:45", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-10-06", "start": "15:30", "end": "17:00", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "Amphi 11", "kind": "class"},
  {"date": "2026-10-06", "start": "16:00", "end": "17:30", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-10-07", "start": "08:30", "end": "10:00", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-10-07", "start": "08:30", "end": "10:00", "course": "GT", "title": "Game theory, applications in economics and finance", "teacher": "Viossat Yannick", "room": "B312", "kind": "class"},
  {"date": "2026-10-07", "start": "10:15", "end": "11:45", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-10-07", "start": "10:15", "end": "11:45", "course": "GT", "title": "Game theory, applications in economics and finance", "teacher": "Viossat Yannick", "room": "B312", "kind": "class"},
  {"date": "2026-10-08", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2026-10-08", "start": "13:45", "end": "15:15", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-10-08", "start": "15:30", "end": "17:00", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-10-09", "start": "08:30", "end": "10:00", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B217", "kind": "class"},
  {"date": "2026-10-09", "start": "10:15", "end": "11:45", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B217", "kind": "class"},
  {"date": "2026-10-12", "start": "08:30", "end": "10:00", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-10-12", "start": "10:15", "end": "11:45", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "C 516", "kind": "class"},
  {"date": "2026-10-12", "start": "13:45", "end": "15:15", "course": "CPP", "title": "C++ / VBA", "teacher": "Cornaz Denis", "room": "A213", "kind": "class"},
  {"date": "2026-10-12", "start": "15:30", "end": "17:00", "course": "CPP", "title": "C++ / VBA", "teacher": "Cornaz Denis", "room": "A213", "kind": "class"},
  {"date": "2026-10-13", "start": "08:30", "end": "10:00", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "F209", "kind": "class"},
  {"date": "2026-10-13", "start": "10:15", "end": "11:45", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "F209", "kind": "class"},
  {"date": "2026-10-13", "start": "13:45", "end": "15:15", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-10-13", "start": "14:15", "end": "15:45", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-10-13", "start": "15:30", "end": "17:00", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-10-13", "start": "16:00", "end": "17:30", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-10-14", "start": "08:30", "end": "10:00", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-10-14", "start": "08:30", "end": "10:00", "course": "GT", "title": "Game theory, applications in economics and finance", "teacher": "Viossat Yannick", "room": "B311", "kind": "class"},
  {"date": "2026-10-14", "start": "10:15", "end": "11:45", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-10-14", "start": "10:15", "end": "11:45", "course": "GT", "title": "Game theory, applications in economics and finance", "teacher": "Viossat Yannick", "room": "B311", "kind": "class"},
  {"date": "2026-10-14", "start": "13:45", "end": "15:15", "course": "SCTD", "title": "Stochastic Calculus — TD", "teacher": "Cosco Clément", "room": "C 516", "kind": "class"},
  {"date": "2026-10-14", "start": "15:30", "end": "17:00", "course": "SCTD", "title": "Stochastic Calculus — TD", "teacher": "Cosco Clément", "room": "C 516", "kind": "class"},
  {"date": "2026-10-15", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2026-10-15", "start": "13:45", "end": "15:15", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-10-15", "start": "15:30", "end": "17:00", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-10-16", "start": "08:30", "end": "10:00", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B215", "kind": "class"},
  {"date": "2026-10-16", "start": "10:15", "end": "11:45", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B215", "kind": "class"},
  {"date": "2026-10-19", "start": "08:30", "end": "10:00", "course": "SCTD", "title": "Stochastic Calculus — TD", "teacher": "Cosco Clément", "room": "C 516", "kind": "class"},
  {"date": "2026-10-19", "start": "10:15", "end": "11:45", "course": "SCTD", "title": "Stochastic Calculus — TD", "teacher": "Cosco Clément", "room": "C 516", "kind": "class"},
  {"date": "2026-10-19", "start": "13:45", "end": "15:15", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "B213", "kind": "class"},
  {"date": "2026-10-19", "start": "15:30", "end": "17:00", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "B213", "kind": "class"},
  {"date": "2026-10-20", "start": "08:30", "end": "10:00", "course": "STC", "title": "Stochastic control", "teacher": "Bergault Philippe", "room": "A311", "kind": "class"},
  {"date": "2026-10-20", "start": "10:15", "end": "11:45", "course": "STC", "title": "Stochastic control", "teacher": "Bergault Philippe", "room": "A311", "kind": "class"},
  {"date": "2026-10-20", "start": "13:45", "end": "15:15", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-10-20", "start": "14:15", "end": "15:45", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-10-20", "start": "15:30", "end": "17:00", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-10-20", "start": "16:00", "end": "17:30", "course": "MC", "title": "Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "class"},
  {"date": "2026-10-21", "start": "08:30", "end": "10:00", "course": "GT", "title": "Game theory, applications in economics and finance", "teacher": "Viossat Yannick", "room": "B311", "kind": "class"},
  {"date": "2026-10-21", "start": "08:30", "end": "10:00", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "A407", "kind": "class"},
  {"date": "2026-10-21", "start": "10:15", "end": "11:45", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "A407", "kind": "class"},
  {"date": "2026-10-21", "start": "10:15", "end": "11:45", "course": "GT", "title": "Game theory, applications in economics and finance", "teacher": "Viossat Yannick", "room": "B311", "kind": "class"},
  {"date": "2026-10-21", "start": "13:45", "end": "15:15", "course": "SCTD", "title": "Stochastic Calculus — TD", "teacher": "Cosco Clément", "room": "C 516", "kind": "class"},
  {"date": "2026-10-21", "start": "15:30", "end": "17:00", "course": "SCTD", "title": "Stochastic Calculus — TD", "teacher": "Cosco Clément", "room": "C 516", "kind": "class"},
  {"date": "2026-10-22", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2026-10-22", "start": "13:45", "end": "15:15", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "AR 52 53", "kind": "class"},
  {"date": "2026-10-22", "start": "15:30", "end": "17:00", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "AR 52 53", "kind": "class"},
  {"date": "2026-10-26", "start": "08:30", "end": "10:00", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "Amphi 11", "kind": "class"},
  {"date": "2026-10-26", "start": "10:15", "end": "11:45", "course": "SC", "title": "Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "Amphi 11", "kind": "class"},
  {"date": "2026-10-26", "start": "13:30", "end": "15:00", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "B206", "kind": "class"},
  {"date": "2026-10-26", "start": "15:15", "end": "16:45", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "B206", "kind": "class"},
  {"date": "2026-10-28", "start": "08:30", "end": "10:00", "course": "GT", "title": "Game theory, applications in economics and finance", "teacher": "Viossat Yannick", "room": "B311", "kind": "class"},
  {"date": "2026-10-28", "start": "08:30", "end": "10:00", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-10-28", "start": "10:15", "end": "11:45", "course": "GT", "title": "Game theory, applications in economics and finance", "teacher": "Viossat Yannick", "room": "B311", "kind": "class"},
  {"date": "2026-10-28", "start": "10:15", "end": "11:45", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-10-29", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2026-11-03", "start": "08:30", "end": "10:00", "course": "STC", "title": "Stochastic control", "teacher": "Bergault Philippe", "room": "A311", "kind": "class"},
  {"date": "2026-11-03", "start": "10:15", "end": "11:45", "course": "STC", "title": "Stochastic control", "teacher": "Bergault Philippe", "room": "A311", "kind": "class"},
  {"date": "2026-11-03", "start": "13:45", "end": "15:15", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-11-03", "start": "15:30", "end": "17:00", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-11-04", "start": "08:30", "end": "10:00", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-11-04", "start": "08:30", "end": "10:00", "course": "GT", "title": "Game theory, applications in economics and finance", "teacher": "Viossat Yannick", "room": "B317", "kind": "class"},
  {"date": "2026-11-04", "start": "10:15", "end": "11:45", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-11-04", "start": "10:15", "end": "11:45", "course": "GT", "title": "Game theory, applications in economics and finance", "teacher": "Viossat Yannick", "room": "B317", "kind": "class"},
  {"date": "2026-11-04", "start": "13:45", "end": "15:15", "course": "SCTD", "title": "Stochastic Calculus — TD", "teacher": "Cosco Clément", "room": "Amphi 10", "kind": "class"},
  {"date": "2026-11-04", "start": "15:30", "end": "17:00", "course": "SCTD", "title": "Stochastic Calculus — TD", "teacher": "Cosco Clément", "room": "Amphi 10", "kind": "class"},
  {"date": "2026-11-05", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2026-11-05", "start": "13:45", "end": "15:15", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-11-05", "start": "15:30", "end": "17:00", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-11-06", "start": "08:30", "end": "10:00", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B215", "kind": "class"},
  {"date": "2026-11-06", "start": "10:15", "end": "11:45", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B215", "kind": "class"},
  {"date": "2026-11-09", "start": "09:00", "end": "12:00", "course": "SC", "title": "Exam — Stochastic Calculus", "teacher": "Hoffmann Marc", "room": "Amphi 1", "kind": "exam"},
  {"date": "2026-11-09", "start": "13:45", "end": "15:15", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "B311", "kind": "class"},
  {"date": "2026-11-09", "start": "15:30", "end": "17:00", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "B311", "kind": "class"},
  {"date": "2026-11-10", "start": "08:30", "end": "10:00", "course": "STC", "title": "Stochastic control", "teacher": "Bergault Philippe", "room": "A311", "kind": "class"},
  {"date": "2026-11-10", "start": "10:15", "end": "11:45", "course": "STC", "title": "Stochastic control", "teacher": "Bergault Philippe", "room": "A311", "kind": "class"},
  {"date": "2026-11-10", "start": "13:45", "end": "15:15", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-11-10", "start": "15:30", "end": "17:00", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-11-12", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2026-11-12", "start": "13:45", "end": "15:15", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-11-12", "start": "15:30", "end": "17:00", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-11-13", "start": "10:15", "end": "11:45", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B215", "kind": "class"},
  {"date": "2026-11-13", "start": "12:00", "end": "13:30", "course": "ML", "title": "Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "B215", "kind": "class"},
  {"date": "2026-11-16", "start": "13:45", "end": "15:15", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "F211", "kind": "class"},
  {"date": "2026-11-16", "start": "15:30", "end": "17:00", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "F211", "kind": "class"},
  {"date": "2026-11-17", "start": "08:30", "end": "10:00", "course": "STC", "title": "Stochastic control", "teacher": "Bergault Philippe", "room": "A311", "kind": "class"},
  {"date": "2026-11-17", "start": "10:15", "end": "11:45", "course": "STC", "title": "Stochastic control", "teacher": "Bergault Philippe", "room": "A311", "kind": "class"},
  {"date": "2026-11-17", "start": "13:45", "end": "15:15", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-11-17", "start": "15:30", "end": "17:00", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-11-18", "start": "08:30", "end": "10:00", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-11-18", "start": "08:30", "end": "10:00", "course": "GT", "title": "Game theory, applications in economics and finance", "teacher": "Viossat Yannick", "room": "B317", "kind": "class"},
  {"date": "2026-11-18", "start": "10:15", "end": "11:45", "course": "T", "title": "Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "D208", "kind": "class"},
  {"date": "2026-11-18", "start": "10:15", "end": "11:45", "course": "GT", "title": "Game theory, applications in economics and finance", "teacher": "Viossat Yannick", "room": "B317", "kind": "class"},
  {"date": "2026-11-18", "start": "13:45", "end": "15:15", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "F211", "kind": "class"},
  {"date": "2026-11-18", "start": "15:30", "end": "17:00", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "F211", "kind": "class"},
  {"date": "2026-11-19", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2026-11-19", "start": "13:45", "end": "15:15", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-11-19", "start": "15:30", "end": "17:00", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-11-20", "start": "08:30", "end": "11:45", "course": "ML", "title": "Exam — Machine Learning in Finance", "teacher": "Brugière Pierre", "room": "Salle A bis", "kind": "exam"},
  {"date": "2026-11-23", "start": "13:45", "end": "15:15", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "F303", "kind": "class"},
  {"date": "2026-11-23", "start": "15:30", "end": "17:00", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "F303", "kind": "class"},
  {"date": "2026-11-24", "start": "08:30", "end": "10:00", "course": "STC", "title": "Stochastic control", "teacher": "Bergault Philippe", "room": "A311", "kind": "class"},
  {"date": "2026-11-24", "start": "10:15", "end": "11:45", "course": "STC", "title": "Stochastic control", "teacher": "Bergault Philippe", "room": "A311", "kind": "class"},
  {"date": "2026-11-25", "start": "08:30", "end": "11:45", "course": "GT", "title": "Exam — Game theory, applications in economics and finance", "teacher": "Viossat Yannick", "room": "C 516", "kind": "exam"},
  {"date": "2026-11-26", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2026-11-26", "start": "13:45", "end": "15:15", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-11-26", "start": "15:30", "end": "17:00", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-11-27", "start": "14:00", "end": "17:00", "course": "T", "title": "Exam — Term structures: theory, models and empirical tests", "teacher": "Lautier Delphine", "room": "Amphi 10", "kind": "exam"},
  {"date": "2026-11-30", "start": "13:45", "end": "15:15", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "F211", "kind": "class"},
  {"date": "2026-11-30", "start": "15:30", "end": "17:00", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "F211", "kind": "class"},
  {"date": "2026-12-01", "start": "08:30", "end": "10:00", "course": "STC", "title": "Stochastic control", "teacher": "Bergault Philippe", "room": "A311", "kind": "class"},
  {"date": "2026-12-01", "start": "10:15", "end": "11:45", "course": "STC", "title": "Stochastic control", "teacher": "Bergault Philippe", "room": "A311", "kind": "class"},
  {"date": "2026-12-01", "start": "13:45", "end": "15:15", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-12-01", "start": "15:30", "end": "17:00", "course": "CO", "title": "Continuous optimization", "teacher": "Chambolle Antonin", "room": "A308", "kind": "class"},
  {"date": "2026-12-03", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2026-12-03", "start": "13:45", "end": "15:15", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-12-03", "start": "15:30", "end": "17:00", "course": "VAL", "title": "Valuation of financial assets and arbitrage", "teacher": "Claisse Julien", "room": "B304", "kind": "class"},
  {"date": "2026-12-07", "start": "13:45", "end": "15:15", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "A304", "kind": "class"},
  {"date": "2026-12-07", "start": "15:30", "end": "17:00", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "A304", "kind": "class"},
  {"date": "2026-12-08", "start": "08:30", "end": "10:00", "course": "STCTD", "title": "Stochastic control — TD", "teacher": "Bergault Philippe", "room": "A301", "kind": "class"},
  {"date": "2026-12-08", "start": "10:15", "end": "11:45", "course": "STCTD", "title": "Stochastic control — TD", "teacher": "Bergault Philippe", "room": "A301", "kind": "class"},
  {"date": "2026-12-08", "start": "14:00", "end": "17:00", "course": "CO", "title": "Exam — Continuous optimization", "teacher": "Chambolle Antonin", "room": "A306", "kind": "exam"},
  {"date": "2026-12-10", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2026-12-11", "start": "09:00", "end": "12:15", "course": "MC", "title": "Exam — Project defences: Computational statistics and MCMC methods", "teacher": "Robert Christian", "room": "ESTRAPADE Amphithéâtre", "kind": "exam"},
  {"date": "2026-12-14", "start": "13:45", "end": "15:15", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "A304", "kind": "class"},
  {"date": "2026-12-14", "start": "15:30", "end": "17:00", "course": "MCF", "title": "Monte Carlo and finite methods with applications to finance", "teacher": "Liu Yating", "room": "A304", "kind": "class"},
  {"date": "2026-12-15", "start": "08:30", "end": "10:00", "course": "STCTD", "title": "Stochastic control — TD", "teacher": "Bergault Philippe", "room": "A301", "kind": "class"},
  {"date": "2026-12-15", "start": "10:15", "end": "11:45", "course": "STCTD", "title": "Stochastic control — TD", "teacher": "Bergault Philippe", "room": "A301", "kind": "class"},
  {"date": "2026-12-17", "start": "10:45", "end": "12:45", "course": "HF", "title": "Finance haute fréquence (Jussieu)", "teacher": "Rosenbaum Mathieu", "room": "Jussieu", "kind": "class"},
  {"date": "2027-01-04", "start": "17:15", "end": "18:45", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "A301", "kind": "class"},
  {"date": "2027-01-04", "start": "19:00", "end": "20:30", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "A301", "kind": "class"},
  {"date": "2027-01-05", "start": "09:00", "end": "12:00", "course": "STC", "title": "Exam — Stochastic control", "teacher": "Bergault Philippe", "room": "", "kind": "exam"},
  {"date": "2027-01-11", "start": "13:45", "end": "15:15", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "A303", "kind": "class"},
  {"date": "2027-01-11", "start": "15:30", "end": "17:00", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "A303", "kind": "class"},
  {"date": "2027-01-25", "start": "10:15", "end": "11:45", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "A301", "kind": "class"},
  {"date": "2027-01-25", "start": "12:00", "end": "13:30", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "A301", "kind": "class"},
  {"date": "2027-01-27", "start": "13:45", "end": "15:15", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "F207", "kind": "class"},
  {"date": "2027-01-27", "start": "15:30", "end": "17:00", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "F207", "kind": "class"},
  {"date": "2027-02-04", "start": "13:45", "end": "15:15", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "F207", "kind": "class"},
  {"date": "2027-02-04", "start": "15:30", "end": "17:00", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "F207", "kind": "class"},
  {"date": "2027-02-11", "start": "13:45", "end": "15:15", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "F207", "kind": "class"},
  {"date": "2027-02-11", "start": "15:30", "end": "17:00", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "F207", "kind": "class"},
  {"date": "2027-02-25", "start": "13:45", "end": "15:15", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "F207", "kind": "class"},
  {"date": "2027-02-25", "start": "15:30", "end": "17:00", "course": "VAR", "title": "Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "F207", "kind": "class"},
  {"date": "2027-03-03", "start": "13:45", "end": "15:15", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "F205", "kind": "class"},
  {"date": "2027-03-03", "start": "15:30", "end": "17:00", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "F205", "kind": "class"},
  {"date": "2027-03-11", "start": "10:15", "end": "11:45", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "F205", "kind": "class"},
  {"date": "2027-03-11", "start": "12:00", "end": "13:30", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "F205", "kind": "class"},
  {"date": "2027-03-18", "start": "10:15", "end": "11:45", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "F205", "kind": "class"},
  {"date": "2027-03-18", "start": "12:00", "end": "13:30", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "F205", "kind": "class"},
  {"date": "2027-03-23", "start": "14:00", "end": "16:00", "course": "VAR", "title": "Exam — Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "Amphi 9", "kind": "exam"},
  {"date": "2027-03-23", "start": "16:00", "end": "16:45", "course": "VAR", "title": "Exam (⅓ temps) — Gestion globale des risques : VaR", "teacher": "Lépinette Emmanuel", "room": "Amphi 10", "kind": "exam-extra"},
  {"date": "2027-03-26", "start": "10:15", "end": "11:45", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "F205", "kind": "class"},
  {"date": "2027-03-26", "start": "12:00", "end": "13:30", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "F205", "kind": "class"},
  {"date": "2027-04-23", "start": "10:15", "end": "11:45", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "Salle A bis", "kind": "class"},
  {"date": "2027-04-23", "start": "12:00", "end": "13:30", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "Salle A bis", "kind": "class"},
  {"date": "2027-04-30", "start": "10:15", "end": "11:45", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "F205", "kind": "class"},
  {"date": "2027-04-30", "start": "12:00", "end": "13:30", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "F205", "kind": "class"},
  {"date": "2027-05-13", "start": "10:15", "end": "11:45", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "Salle B bis", "kind": "class"},
  {"date": "2027-05-13", "start": "12:00", "end": "13:30", "course": "RATES", "title": "Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "Salle B bis", "kind": "class"},
  {"date": "2027-05-27", "start": "10:00", "end": "13:00", "course": "RATES", "title": "Exam — Modélisation stochastique de la courbe de taux (app)", "teacher": "Ben Tahar Imen", "room": "Salle C bis", "kind": "exam"},
  {"date": "2027-05-27", "start": "13:00", "end": "14:00", "course": "RATES", "title": "Exam (⅓ temps) — Modélisation stochastique de la courbe de taux (app)", "teacher": "Mhiri Wafa", "room": "Salle C bis", "kind": "exam-extra"},
];
